-- =============================================================
-- SNOWFLAKE DATA WAREHOUSE SETUP
-- =============================================================
-- Run this against your Snowflake account to initialize the warehouse.
-- Usage: snowsql -a <account> -u <user> -f snowflake/init_warehouse.sql

-- =====================
-- Infrastructure Setup
-- =====================
CREATE WAREHOUSE IF NOT EXISTS PIPELINE_WH
    WITH WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'E2E Data Pipeline warehouse';

CREATE DATABASE IF NOT EXISTS PIPELINE_DB;
CREATE SCHEMA IF NOT EXISTS PIPELINE_DB.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS PIPELINE_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS PIPELINE_DB.RAW;

USE WAREHOUSE PIPELINE_WH;
USE DATABASE PIPELINE_DB;
USE SCHEMA ANALYTICS;

-- Internal stage for file loading
CREATE STAGE IF NOT EXISTS PIPELINE_STAGE
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

-- =====================
-- Dimension Tables
-- =====================
CREATE TABLE IF NOT EXISTS DIM_CUSTOMERS (
    CUSTOMER_KEY INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT UNIQUE NOT NULL,
    CUSTOMER_NAME VARCHAR(100),
    CUSTOMER_SEGMENT VARCHAR(50) DEFAULT 'Standard',
    JOIN_DATE TIMESTAMP_NTZ,
    EFFECTIVE_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_TO TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS DIM_DATE (
    DATE_KEY INT PRIMARY KEY,
    FULL_DATE DATE NOT NULL,
    DAY_OF_WEEK INT,
    DAY_NAME VARCHAR(10),
    DAY_OF_MONTH INT,
    DAY_OF_YEAR INT,
    WEEK_OF_YEAR INT,
    MONTH_NUM INT,
    MONTH_NAME VARCHAR(10),
    QUARTER INT,
    YEAR INT,
    IS_WEEKEND BOOLEAN,
    IS_HOLIDAY BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS DIM_PRODUCTS (
    PRODUCT_KEY INT AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID INT UNIQUE,
    PRODUCT_NAME VARCHAR(200),
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    UNIT_PRICE DECIMAL(10,2),
    EFFECTIVE_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_CURRENT BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS DIM_DEVICES (
    DEVICE_KEY INT AUTOINCREMENT PRIMARY KEY,
    DEVICE_ID INT UNIQUE NOT NULL,
    DEVICE_NAME VARCHAR(100),
    DEVICE_TYPE VARCHAR(50) DEFAULT 'sensor',
    LOCATION VARCHAR(200),
    INSTALL_DATE TIMESTAMP_NTZ,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- =====================
-- Fact Tables
-- =====================
CREATE TABLE IF NOT EXISTS FACT_ORDERS (
    ORDER_KEY INT AUTOINCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    CUSTOMER_KEY INT REFERENCES DIM_CUSTOMERS(CUSTOMER_KEY),
    DATE_KEY INT REFERENCES DIM_DATE(DATE_KEY),
    ORDER_AMOUNT DECIMAL(10,2) NOT NULL,
    QUANTITY INT DEFAULT 1,
    DISCOUNT_AMOUNT DECIMAL(10,2) DEFAULT 0,
    NET_AMOUNT DECIMAL(10,2),
    PROCESSED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'mysql'
);

CREATE TABLE IF NOT EXISTS FACT_SENSOR_READINGS (
    READING_KEY INT AUTOINCREMENT PRIMARY KEY,
    DEVICE_KEY INT REFERENCES DIM_DEVICES(DEVICE_KEY),
    DATE_KEY INT REFERENCES DIM_DATE(DATE_KEY),
    EVENT_ID VARCHAR(50),
    READING_VALUE DOUBLE NOT NULL,
    IS_ANOMALY BOOLEAN DEFAULT FALSE,
    ANOMALY_SCORE DOUBLE,
    READING_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    PROCESSED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FACT_PIPELINE_RUNS (
    RUN_KEY INT AUTOINCREMENT PRIMARY KEY,
    DAG_ID VARCHAR(100) NOT NULL,
    RUN_ID VARCHAR(200),
    RUN_TYPE VARCHAR(50),
    START_TIME TIMESTAMP_NTZ,
    END_TIME TIMESTAMP_NTZ,
    DURATION_SECONDS INT,
    STATUS VARCHAR(20),
    RECORDS_PROCESSED INT DEFAULT 0,
    RECORDS_FAILED INT DEFAULT 0,
    ERROR_MESSAGE TEXT
);

-- =====================
-- Aggregation Tables
-- =====================
CREATE TABLE IF NOT EXISTS AGG_DAILY_ORDERS (
    DATE_KEY INT PRIMARY KEY,
    TOTAL_ORDERS INT,
    TOTAL_REVENUE DECIMAL(12,2),
    AVG_ORDER_VALUE DECIMAL(10,2),
    UNIQUE_CUSTOMERS INT,
    MAX_ORDER_VALUE DECIMAL(10,2),
    MIN_ORDER_VALUE DECIMAL(10,2),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS AGG_HOURLY_SENSORS (
    ID INT AUTOINCREMENT PRIMARY KEY,
    DEVICE_KEY INT REFERENCES DIM_DEVICES(DEVICE_KEY),
    HOUR_START TIMESTAMP_NTZ NOT NULL,
    READING_COUNT INT,
    AVG_READING DOUBLE,
    MIN_READING DOUBLE,
    MAX_READING DOUBLE,
    ANOMALY_COUNT INT DEFAULT 0,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE(DEVICE_KEY, HOUR_START)
);

-- =====================
-- Staging Tables (for ingestion)
-- =====================
CREATE TABLE IF NOT EXISTS STAGING.STG_ORDERS (
    ORDER_ID INT,
    CUSTOMER_ID INT,
    AMOUNT DECIMAL(10,2),
    PROCESSED_TIMESTAMP TIMESTAMP_NTZ,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS STAGING.STG_SENSOR_READINGS (
    EVENT_ID VARCHAR(50),
    DEVICE_ID INT,
    READING_VALUE DOUBLE,
    IS_ANOMALY BOOLEAN,
    READING_TIMESTAMP TIMESTAMP_NTZ,
    PROCESSED_AT TIMESTAMP_NTZ,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =====================
-- Populate DIM_DATE (2024-2026)
-- =====================
INSERT INTO DIM_DATE (DATE_KEY, FULL_DATE, DAY_OF_WEEK, DAY_NAME, DAY_OF_MONTH, DAY_OF_YEAR, WEEK_OF_YEAR, MONTH_NUM, MONTH_NAME, QUARTER, YEAR, IS_WEEKEND)
SELECT
    TO_NUMBER(TO_CHAR(d.DAY, 'YYYYMMDD')) AS DATE_KEY,
    d.DAY::DATE AS FULL_DATE,
    DAYOFWEEK(d.DAY) AS DAY_OF_WEEK,
    DAYNAME(d.DAY) AS DAY_NAME,
    DAY(d.DAY) AS DAY_OF_MONTH,
    DAYOFYEAR(d.DAY) AS DAY_OF_YEAR,
    WEEKOFYEAR(d.DAY) AS WEEK_OF_YEAR,
    MONTH(d.DAY) AS MONTH_NUM,
    MONTHNAME(d.DAY) AS MONTH_NAME,
    QUARTER(d.DAY) AS QUARTER,
    YEAR(d.DAY) AS YEAR,
    DAYOFWEEK(d.DAY) IN (0, 6) AS IS_WEEKEND
FROM (
    SELECT DATEADD(DAY, seq4(), '2024-01-01'::DATE) AS DAY
    FROM TABLE(GENERATOR(ROWCOUNT => 1096))
) d
WHERE d.DAY <= '2026-12-31'::DATE
AND NOT EXISTS (SELECT 1 FROM DIM_DATE dd WHERE dd.DATE_KEY = TO_NUMBER(TO_CHAR(d.DAY, 'YYYYMMDD')));

-- =====================
-- Clustering Keys (Snowflake-specific optimization)
-- =====================
ALTER TABLE FACT_ORDERS CLUSTER BY (DATE_KEY, CUSTOMER_KEY);
ALTER TABLE FACT_SENSOR_READINGS CLUSTER BY (DATE_KEY, DEVICE_KEY);
ALTER TABLE FACT_PIPELINE_RUNS CLUSTER BY (DAG_ID, START_TIME);

-- =====================
-- Snowflake Tasks (automated ETL scheduling)
-- =====================
CREATE OR REPLACE TASK REFRESH_DAILY_ORDERS_AGG
    WAREHOUSE = PIPELINE_WH
    SCHEDULE = 'USING CRON 0 * * * * UTC'
AS
MERGE INTO AGG_DAILY_ORDERS tgt
USING (
    SELECT
        DATE_KEY,
        COUNT(*) AS TOTAL_ORDERS,
        SUM(NET_AMOUNT) AS TOTAL_REVENUE,
        AVG(NET_AMOUNT) AS AVG_ORDER_VALUE,
        COUNT(DISTINCT CUSTOMER_KEY) AS UNIQUE_CUSTOMERS,
        MAX(NET_AMOUNT) AS MAX_ORDER_VALUE,
        MIN(NET_AMOUNT) AS MIN_ORDER_VALUE
    FROM FACT_ORDERS
    GROUP BY DATE_KEY
) src ON tgt.DATE_KEY = src.DATE_KEY
WHEN MATCHED THEN UPDATE SET
    tgt.TOTAL_ORDERS = src.TOTAL_ORDERS,
    tgt.TOTAL_REVENUE = src.TOTAL_REVENUE,
    tgt.AVG_ORDER_VALUE = src.AVG_ORDER_VALUE,
    tgt.UNIQUE_CUSTOMERS = src.UNIQUE_CUSTOMERS,
    tgt.MAX_ORDER_VALUE = src.MAX_ORDER_VALUE,
    tgt.MIN_ORDER_VALUE = src.MIN_ORDER_VALUE,
    tgt.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT VALUES (
    src.DATE_KEY, src.TOTAL_ORDERS, src.TOTAL_REVENUE,
    src.AVG_ORDER_VALUE, src.UNIQUE_CUSTOMERS,
    src.MAX_ORDER_VALUE, src.MIN_ORDER_VALUE, CURRENT_TIMESTAMP()
);

-- Enable the task
ALTER TASK REFRESH_DAILY_ORDERS_AGG RESUME;

-- =====================
-- Grants
-- =====================
GRANT USAGE ON WAREHOUSE PIPELINE_WH TO ROLE PIPELINE_ROLE;
GRANT USAGE ON DATABASE PIPELINE_DB TO ROLE PIPELINE_ROLE;
GRANT USAGE ON SCHEMA PIPELINE_DB.ANALYTICS TO ROLE PIPELINE_ROLE;
GRANT USAGE ON SCHEMA PIPELINE_DB.STAGING TO ROLE PIPELINE_ROLE;
GRANT USAGE ON SCHEMA PIPELINE_DB.RAW TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PIPELINE_DB.ANALYTICS TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PIPELINE_DB.STAGING TO ROLE PIPELINE_ROLE;
GRANT USAGE ON STAGE PIPELINE_DB.ANALYTICS.PIPELINE_STAGE TO ROLE PIPELINE_ROLE;
