apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secrets
  namespace: {{ include "e2e-pipeline.namespace" . }}
  labels:
    {{- include "e2e-pipeline.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.postgresql.auth.username }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password }}"
  MYSQL_USER: "{{ .Values.mysql.auth.username }}"
  MYSQL_PASSWORD: "{{ .Values.mysql.auth.password }}"
  MINIO_ROOT_USER: "{{ .Values.minio.auth.rootUser }}"
  MINIO_ROOT_PASSWORD: "{{ .Values.minio.auth.rootPassword }}"
  AIRFLOW_ADMIN_USER: "{{ .Values.airflow.auth.username }}"
  AIRFLOW_ADMIN_PASSWORD: "{{ .Values.airflow.auth.password }}"
  {{- if .Values.snowflake.enabled }}
  SNOWFLAKE_ACCOUNT: "{{ .Values.snowflake.account }}"
  SNOWFLAKE_USER: "{{ .Values.snowflake.user }}"
  SNOWFLAKE_PASSWORD: "{{ .Values.snowflake.password }}"
  {{- end }}
